drop table transactions if exists;

create table transactions (
    id bigint generated by default as identity primary key,
    typeId integer not null,
    timeMs integer not null,
    userId bigint not null,
    amount double
);

